apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: victoria-metrics-vmagent
spec:
  logFormat: {{ .Values.vmagent.logFormat }}
  logLevel: {{ .Values.vmagent.logLevel }}
  replicaCount: {{ .Values.vmagent.replicaCount }}
  scrapeInterval: {{ .Values.vmagent.scrapeInterval }}
  imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 4 }}
  serviceScrapeNamespaceSelector: {}
  podScrapeNamespaceSelector: {}
  podScrapeSelector: {}
  serviceScrapeSelector: {}
  nodeScrapeSelector: {}
  nodeScrapeNamespaceSelector: {}
  staticScrapeSelector: {}
  staticScrapeNamespaceSelector: {}
  remoteWrite:
{{ toYaml .Values.vmagent.remoteWrite | indent 4 }}
  statefulMode: {{ .Values.vmagent.statefulMode }}
  statefulStorage:
    volumeClaimTemplate:
      spec:
        storageClassName: {{ .Values.vmagent.statefulStorage.storageClassName }}
        volumeMode: {{ .Values.vmagent.statefulStorage.volumeMode }}
        volumeName: {{ .Values.vmagent.statefulStorage.volumeName }}
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.vmagent.statefulStorage.size }}
{{- with .Values.nodeSelector }}
  nodeSelector:
{{ toYaml . | indent 4 }}
{{- end }}
  tolerations:
{{ toYaml .Values.tolerations | indent 4 }}