{{- if .Values.vmagent.relabel.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.vmagent.urlRelabelConfig.name }}
data:
{{- range $key, $value := .Values.vmagent.relabelconfig }}
{{ $key | indent 2}}: |-
{{ $value | indent 4}}
{{- end }}
{{- end }}
