apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlertmanager
metadata:
  name: victoria-metrics-alertmanager
spec:
  podMetadata:
    labels:
      release: {{ .Release.Name }}
  imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 4 }}
  logFormat: {{ .Values.vmalertmanager.logFormat }}
  replicaCount: {{ .Values.vmalertmanager.replicaCount }}
  selectAllByDefault: {{ .Values.vmalertmanager.selectAllByDefault }}
  configSecret: {{ .Values.vmalertmanager.configSecret }}
{{- with .Values.nodeSelector }}
  nodeSelector:
{{ toYaml . | indent 4 }}
{{- end }}
  tolerations:
{{ toYaml .Values.tolerations | indent 4 }}