{{- if .Values.vmalertmanager.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/instance: vmalertmanager-victoria-metrics-alertmanager
    app.kubernetes.io/name: vmalertmanager-victoria-metrics-alertmanager
  name: vmalertmanager-victoria-metrics-alertmanager
  namespace: monitoring
spec:
  ingressClassName: {{ .Values.vmalertmanager.ingress.ingressClassName }}
  rules:
  - host: {{ .Values.vmalertmanager.ingress.host }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Values.vmalertmanager.ingress.serviceName }}
            port:
              number: {{ .Values.vmalertmanager.ingress.servicePort }}
        path: /
        pathType: Prefix
{{- end }}