apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlert
metadata:
  name: victoria-metrics-alertserver
spec:
  logFormat: {{ .Values.vmalert.logFormat }}
  logLevel: {{ .Values.vmalert.logLevel }}
  imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 4 }}
  replicaCount: {{ .Values.vmalert.replicaCount }}
{{- with .Values.vmalert.remoteWrite }}
  remoteWrite:
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.vmalert.datasource }}
  datasource:
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.vmalert.notifier }}
  notifier:
{{ toYaml . | indent 4 }}
{{- end }}
  evaluationInterval: {{ .Values.vmalert.evaluationInterval | quote }}
  ruleNamespaceSelector: {}
  ruleSelector: {}
{{- with .Values.nodeSelector }}
  nodeSelector:
{{ toYaml . | indent 4 }}
{{- end }}
  tolerations:
{{ toYaml .Values.tolerations | indent 4 }}