{{- if .Values.vmrule.enabled -}}
{{- $top := . }}
{{- range .Values.vmrule.config }}
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  name: vmrule-{{ .name }}
  labels:
    cluster: univ-prod
spec:
  groups:
{{ toYaml .groups | indent 2 }}
{{- end }}
{{- end }}