apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: victoria-metrics-single
spec:
  podMetadata:
    labels:
      release: {{ .Release.Name }}
  logFormat: {{ .Values.vmsingle.logFormat }}
  logLevel: {{ .Values.vmsingle.logLevel }}
  dnsPolicy: {{ .Values.vmsingle.dnsPolicy }}
  replicaCount: {{ .Values.vmsingle.replicaCount }}
  retentionPeriod: {{ .Values.vmsingle.retentionPeriod | quote }}
  removePvcAfterDelete: {{ .Values.vmsingle.removePvcAfterDelete }}
  imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 4 }}
  storage:
    storageClassName: {{ .Values.vmsingle.storage.storageClassName }}
    volumeMode: {{ .Values.vmsingle.storage.volumeMode }}
    volumeName: {{ .Values.vmsingle.storage.volumeName }}
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: {{ .Values.vmsingle.storage.size }}
{{- with .Values.nodeSelector }}
  nodeSelector:
{{ toYaml . | indent 4 }}
{{- end }}
  tolerations:
{{ toYaml .Values.tolerations | indent 4 }}