{{- if .Values.vmstaticscrape.enabled -}}
{{- $top := . }}
{{- range .Values.vmstaticscrape.config }}
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMStaticScrape
metadata:
  name: vmstaticscrape-{{ .name }}
spec:
  jobName: {{ .name $top }}
  targetEndpoints:
{{ toYaml .targetEndpoints | indent 4 }}
{{- end }}
{{- end }}